// Generated by test.json
import React from 'react';
import './component_1.css';


export default class Component_1 extends React.Component {
  render() {
    return (
      <div className="component_1-component_1">
          <div className="component_1-0">
              <div className="component_1-0-0">
                  <div className="component_1-0-0-0">
                      <div className="component_1-rectangle-9" /> 
                  </div>
              </div>
              <div className="component_1-rectangle-6" /> 
          </div>
      </div>
    );
  }
};
